//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 11:17:39 AM CET 
//


package applicationJaxbRes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the applicationJaxbRes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: applicationJaxbRes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Application.Requirement }
     * 
     */
    public Application.Requirement createApplicationRequirement() {
        return new Application.Requirement();
    }

    /**
     * Create an instance of {@link Application.Requirement.Companies }
     * 
     */
    public Application.Requirement.Companies createApplicationRequirementCompanies() {
        return new Application.Requirement.Companies();
    }

    /**
     * Create an instance of {@link Application.Person }
     * 
     */
    public Application.Person createApplicationPerson() {
        return new Application.Person();
    }

    /**
     * Create an instance of {@link Application.Reference }
     * 
     */
    public Application.Reference createApplicationReference() {
        return new Application.Reference();
    }

    /**
     * Create an instance of {@link Application.Requirement.Contract }
     * 
     */
    public Application.Requirement.Contract createApplicationRequirementContract() {
        return new Application.Requirement.Contract();
    }

    /**
     * Create an instance of {@link Application.Requirement.Field }
     * 
     */
    public Application.Requirement.Field createApplicationRequirementField() {
        return new Application.Requirement.Field();
    }

    /**
     * Create an instance of {@link Application.Requirement.Companies.Company }
     * 
     */
    public Application.Requirement.Companies.Company createApplicationRequirementCompaniesCompany() {
        return new Application.Requirement.Companies.Company();
    }

}
