//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 04:29:16 PM CET 
//


package resultJaxRes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the resultJaxRes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Profile_QNAME = new QName("result", "Profile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: resultJaxRes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordsType }
     * 
     */
    public RecordsType createRecordsType() {
        return new RecordsType();
    }

    /**
     * Create an instance of {@link RecordsType.Person }
     * 
     */
    public RecordsType.Person createRecordsTypePerson() {
        return new RecordsType.Person();
    }

    /**
     * Create an instance of {@link DegreeType }
     * 
     */
    public DegreeType createDegreeType() {
        return new DegreeType();
    }

    /**
     * Create an instance of {@link DegreeType.Program }
     * 
     */
    public DegreeType.Program createDegreeTypeProgram() {
        return new DegreeType.Program();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link ApplicationType.Requirement }
     * 
     */
    public ApplicationType.Requirement createApplicationTypeRequirement() {
        return new ApplicationType.Requirement();
    }

    /**
     * Create an instance of {@link ApplicationType.Requirement.Companies }
     * 
     */
    public ApplicationType.Requirement.Companies createApplicationTypeRequirementCompanies() {
        return new ApplicationType.Requirement.Companies();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfileType() {
        return new Profile();
    }

    /**
     * Create an instance of {@link CompaniesType }
     * 
     */
    public CompaniesType createCompaniesType() {
        return new CompaniesType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link OfficeType }
     * 
     */
    public OfficeType createOfficeType() {
        return new OfficeType();
    }

    /**
     * Create an instance of {@link RecordsType.Person.Work }
     * 
     */
    public RecordsType.Person.Work createRecordsTypePersonWork() {
        return new RecordsType.Person.Work();
    }

    /**
     * Create an instance of {@link DegreeType.University }
     * 
     */
    public DegreeType.University createDegreeTypeUniversity() {
        return new DegreeType.University();
    }

    /**
     * Create an instance of {@link DegreeType.PersonalInfo }
     * 
     */
    public DegreeType.PersonalInfo createDegreeTypePersonalInfo() {
        return new DegreeType.PersonalInfo();
    }

    /**
     * Create an instance of {@link DegreeType.Program.Course }
     * 
     */
    public DegreeType.Program.Course createDegreeTypeProgramCourse() {
        return new DegreeType.Program.Course();
    }

    /**
     * Create an instance of {@link ApplicationType.Person }
     * 
     */
    public ApplicationType.Person createApplicationTypePerson() {
        return new ApplicationType.Person();
    }

    /**
     * Create an instance of {@link ApplicationType.Reference }
     * 
     */
    public ApplicationType.Reference createApplicationTypeReference() {
        return new ApplicationType.Reference();
    }

    /**
     * Create an instance of {@link ApplicationType.Requirement.Contract }
     * 
     */
    public ApplicationType.Requirement.Contract createApplicationTypeRequirementContract() {
        return new ApplicationType.Requirement.Contract();
    }

    /**
     * Create an instance of {@link ApplicationType.Requirement.Field }
     * 
     */
    public ApplicationType.Requirement.Field createApplicationTypeRequirementField() {
        return new ApplicationType.Requirement.Field();
    }

    /**
     * Create an instance of {@link ApplicationType.Requirement.Companies.Company }
     * 
     */
    public ApplicationType.Requirement.Companies.Company createApplicationTypeRequirementCompaniesCompany() {
        return new ApplicationType.Requirement.Companies.Company();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "result", name = "Profile")
    public JAXBElement<Profile> createProfile(Profile value) {
        return new JAXBElement<Profile>(_Profile_QNAME, Profile.class, null, value);
    }

}
