//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 04:29:16 PM CET 
//


package resultJaxRes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for profileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Application" type="{result}applicationType"/>
 *         &lt;element name="Degree" type="{result}degreeType"/>
 *         &lt;element name="Records" type="{result}recordsType"/>
 *         &lt;element name="Companies" type="{result}companiesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profileType", propOrder = {
    "application",
    "degree",
    "records",
    "companies"
})
@XmlRootElement
public class Profile {

    @XmlElement(name = "Application", required = true)
    protected ApplicationType application;
    @XmlElement(name = "Degree", required = true)
    protected DegreeType degree;
    @XmlElement(name = "Records", required = true)
    protected RecordsType records;
    @XmlElement(name = "Companies", required = true)
    protected CompaniesType companies;

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationType }
     *     
     */
    public ApplicationType getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationType }
     *     
     */
    public void setApplication(ApplicationType value) {
        this.application = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeType }
     *     
     */
    public DegreeType getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeType }
     *     
     */
    public void setDegree(DegreeType value) {
        this.degree = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link RecordsType }
     *     
     */
    public RecordsType getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordsType }
     *     
     */
    public void setRecords(RecordsType value) {
        this.records = value;
    }

    /**
     * Gets the value of the companies property.
     * 
     * @return
     *     possible object is
     *     {@link CompaniesType }
     *     
     */
    public CompaniesType getCompanies() {
        return companies;
    }

    /**
     * Sets the value of the companies property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompaniesType }
     *     
     */
    public void setCompanies(CompaniesType value) {
        this.companies = value;
    }

}
