//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 03:17:17 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "university", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package degreeJaxRes;
